export { loginAPI } from './modules/login'
export { UserAPI } from './modules/user'
export { SongAPI } from './modules/song'
export { SearchAPI } from './modules/search'
export { PlaylistAPI } from './modules/playlist'
export { RecommendAPI } from './modules/recommend'
